export const GET_SKILLS = 'GET_SKILLS';
export const SET_SKILLS = 'SET_SKILLS';
export const SET_TO_ZERO_SKILLS = 'SET_TO_ZERO_SKILLS';

export const SET_SKILL_TITLE = 'SET_SKILL_TITLE';
export const SET_SKILL_PERCENTS = 'SET_SKILL_PERCENTS';
export const SET_TO_ZERO_SKILL_FORMS = 'SET_TO_ZERO_SKILL_FORMS';
export const SET_TO_ZERO_SKILL_FORM = 'SET_TO_ZERO_SKILL_FORM';

export const CREATE_SKILL = 'CREATE_SKILL';
export const PATCH_SKILL = 'PATCH_SKILL';
export const DELETE_SKILL = 'DELETE_SKILL';

export const DEFINE_SKILL_ITEM = 'DEFINE_SKILL_ITEM';

export const VALIDATE_SKILL = 'VALIDATE_SKILL';
export const PUSH_SKILL = 'PUSH_SKILL';
export const REMOVE_SKILL = 'REMOVE_SKILL';
export const REPLACE_SKILL = 'REPLACE_SKILL';
export const CHOOSE_SKILL_FOR_EDIT = 'CHOOSE_SKILL_FOR_EDIT';